# Generated by Django 5.0.4 on 2024-04-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('max_similarity', models.FloatField()),
                ('most_similar_question', models.TextField()),
                ('most_similar_answer', models.TextField()),
            ],
        ),
    ]
